version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Install dependencies node modules with yarn.
      - npm_config_build_from_source=true yarn install --ignore-engines
  build:
    commands:
      - yarn build-all
      - yarn migrate
  post_build:
    commands:
      - echo PWD
      - pwd
      - zip -r output.zip * -x scripts/**\* *.yml
artifacts:
  files:
    - output.zip
    - appspec.yml
    - scripts/**/*
    - config/**/*